[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
dapp_diary = "DJYHqZPeSeQZgqTAqifgKm1AXSaN3RTCTsWxzsSPdqNR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/sandatang/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
