[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
tododapp = "69vftSwP1vaHhfuv5ssuysmmkwAo1e48Aw3tEmRWkRCq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/sandatang/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
